import Head from "next/head";
import { Inter } from "next/font/google";
import { supabase } from "@/lib/supabaseInstance";
import { useRouter } from "next/router";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Login() {
  const router = useRouter();

  async function retrieveSession() {

    const {
      data: { user },
    } = await supabase.auth.getUser();

    // si existe un usuario, redirigir a siguiente pantalla
    if (user) {
      router.push("/stats");
    } else {
      // UI feedback de que no se puedo loguear el usuario
      console.log("no se pudo hacer login");
      router.push("/");
    }
  }

  async function loginToSpotify() {
    console.log("loggin in to spotify");

    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: "spotify",
      options: {
        scopes: "user-top-read",
        redirectTo: "http://localhost:3000/stats",
      },
    });


  }

  return (
    <>
      <Head>
        <title>Musicstats.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="home">
        <img          
          id="logo"
          className="h-auto max-w-xs"
          src="img/logo.jpg"                    
          alt="logo"
        />
        <img        
          id="i-1"  
          className="h-auto max-w-xs"
          src="img/logo.jpg"                    
          alt="logo"
        />
        <img    
          id="i-2"      
          className="h-auto max-w-xs"
          src="img/logo.jpg"                    
          alt="logo"
        />
        <img   
          id="i-3"       
          className="h-auto max-w-xs"
          src="img/logo.jpg"                    
          alt="logo"
        />
        <img   
          id="i-4"       
          className="h-auto max-w-xs"
          src="img/logo.jpg"                    
          alt="logo"
        />
        <img   
          id="i-5"       
          className="h-auto max-w-xs"
          src="img/logo.jpg"                    
          alt="logo"
        />
        <img   
          id="i-6" 
          className="h-auto max-w-xs"
          src="img/logo.jpg"                    
          alt="logo"
        />
        <img   
          id="i-7"       
          className="h-auto max-w-xs"
          src="img/logo.jpg"                    
          alt="logo"
        />
        <button
          id="login"
          type="button"
          onClick={loginToSpotify}
          className="rounded-lg bg-gray-800 px-5 py-2.5 text-sm font-medium text-white"
        >
          Log in with Spotify
        </button>
      </div>
      
    </>
  );
}
