import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { supabase } from "@/lib/supabaseInstance";
import { useRouter } from "next/router";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Login() {
  const router = useRouter();

  async function retrieveSession() {

    const {
      data: { user },
    } = await supabase.auth.getUser();

    // si existe un usuario, redirigir a siguiente pantalla
    if (user) {
      router.push("/stats");
    } else {
      // UI feedback de que no se puedo loguear el usuario
      console.log("no se pudo hacer login");
      router.push("/");
    }
  }

  async function loginToSpotify() {
    console.log("loggin in to spotify");

    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: "spotify",
      options: {
        scopes: "user-top-read",
        redirectTo: "http://localhost:3000/stats",
      },
    });


  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="flex items-center text-neutral-900">Tailwind CSS</h1>
      <button className="bg-orange-400" onClick={loginToSpotify}>
        Spotify login
      </button>

      <button className="bg-blue-400" onClick={retrieveSession}>
        GET SESSION
      </button>
    </>
  );
}
