import Head from "next/head";
import { Inter } from "next/font/google";

export default function TracksArtistas() {
  return (
    <>
      <Head>
        <title>Musicstats.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="seccion-tracks-artistas">
        <div className="heading">
          <h1>Tracks / Artistas</h1>
        </div>
        <div className="imgs-container">
          <img
            className="rounded-full"
            src="/img/default-img.png"
            alt="image description"
          />
          <img
            className="rounded-full"
            src="/img/default-img.png"
            alt="image description"
          />
          <img
            className="rounded-full"
            src="/img/default-img.png"
            alt="image description"
          />
          <img
            className="rounded-full"
            src="/img/default-img.png"
            alt="image description"
          />
          <img
            className="rounded-full"
            src="/img/default-img.png"
            alt="image description"
          />
          <img
            className="rounded-full"
            src="/img/default-img.png"
            alt="image description"
          />
          <img
            className="rounded-full"
            src="/img/default-img.png"
            alt="image description"
          />
          <img
            className="rounded-full"
            src="/img/default-img.png"
            alt="image description"
          />
        </div>
      </div>
    </>
  );
}
